export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/admin/auth/login',
    LOGOUT: '/admin/auth/logout',
    ME: '/admin/auth/me',
    FORGOT_PASSWORD: '/admin/auth/forgot-password',
  },
  DASHBOARD: {
    OVERVIEW: '/admin/dashboard',
  },
  STUDENTS: {
    LIST: '/admin/students',
    DETAILS: (id: string) => `/admin/students/${id}`,
    UPDATE_STATUS: (id: string) => `/admin/students/${id}/status`,
    DELETE: (id: string) => `/admin/students/${id}`,
    BOOKINGS: (id: string) => `/admin/students/${id}/bookings`,
  },
  ARTISANS: {
    LIST: '/admin/artisans',
    DETAILS: (id: string) => `/admin/artisans/${id}`,
    UPDATE_STATUS: (id: string) => `/admin/artisans/${id}/status`,
    VERIFY: (id: string) => `/admin/artisans/${id}/verify`,
    DELETE: (id: string) => `/admin/artisans/${id}`,
    PORTFOLIO: (id: string) => `/admin/artisans/${id}/portfolio`,
    REVIEWS: (id: string) => `/admin/artisans/${id}/reviews`,
    BOOKINGS: (id: string) => `/admin/artisans/${id}/bookings`,
    DOCUMENTS: (id: string) => `/admin/artisans/${id}/documents`,
  },
  VERIFICATIONS: {
    LIST: '/admin/verifications',
    DETAILS: (id: string) => `/admin/verifications/${id}`,
    APPROVE: (id: string) => `/admin/verifications/${id}/approve`,
    REJECT: (id: string) => `/admin/verifications/${id}/reject`,
    REQUEST_INFO: (id: string) => `/admin/verifications/${id}/request-info`,
    DOCUMENTS: (id: string) => `/admin/verifications/${id}/documents`,
    STATISTICS: '/admin/verifications/statistics',
  },
  CATEGORIES: {
    LIST: '/admin/categories',
    DETAILS: (id: string) => `/admin/categories/${id}`,
    CREATE: '/admin/categories',
    UPDATE: (id: string) => `/admin/categories/${id}`,
    UPDATE_STATUS: (id: string) => `/admin/categories/${id}/status`,
    REORDER: '/admin/categories/reorder',
    DELETE: (id: string) => `/admin/categories/${id}`,
    STATISTICS: (id: string) => `/admin/categories/${id}/statistics`,
    OVERVIEW_STATISTICS: '/admin/categories/statistics',
  },
  BOOKINGS: {
    LIST: '/admin/bookings',
    DETAILS: (id: string) => `/admin/bookings/${id}`,
    UPDATE_STATUS: (id: string) => `/admin/bookings/${id}/status`,
    CANCEL: (id: string) => `/admin/bookings/${id}/cancel`,
    COMPLETE: (id: string) => `/admin/bookings/${id}/complete`,
    RESOLVE_DISPUTE: (id: string) => `/admin/bookings/${id}/resolve-dispute`,
    TIMELINE: (id: string) => `/admin/bookings/${id}/timeline`,
    STATISTICS: '/admin/bookings/statistics',
    EXPORT: '/admin/bookings/export',
  },
  REVIEWS: {
    LIST: '/admin/reviews',
    DETAILS: (id: string) => `/admin/reviews/${id}`,
    UPDATE_STATUS: (id: string) => `/admin/reviews/${id}/status`,
    HIDE: (id: string) => `/admin/reviews/${id}/hide`,
    RESTORE: (id: string) => `/admin/reviews/${id}/restore`,
    FLAG: (id: string) => `/admin/reviews/${id}/flag`,
    DELETE: (id: string) => `/admin/reviews/${id}`,
    STATISTICS: '/admin/reviews/statistics',
    EXPORT: '/admin/reviews/export',
  },
  REPORTS: {
    LIST: '/admin/reports',
    DETAILS: (id: string) => `/admin/reports/${id}`,
    UPDATE_STATUS: (id: string) => `/admin/reports/${id}/status`,
    ASSIGN: (id: string) => `/admin/reports/${id}/assign`,
    RESOLVE: (id: string) => `/admin/reports/${id}/resolve`,
    DISMISS: (id: string) => `/admin/reports/${id}/dismiss`,
    NOTES: (id: string) => `/admin/reports/${id}/notes`,
    STATISTICS: '/admin/reports/statistics',
    EXPORT: '/admin/reports/export',
  },
  ANALYTICS: {
    OVERVIEW: '/admin/analytics/overview',
    USERS: '/admin/analytics/users',
    BOOKINGS: '/admin/analytics/bookings',
    REVENUE: '/admin/analytics/revenue',
    CATEGORIES: '/admin/analytics/categories',
    REVIEWS: '/admin/analytics/reviews',
    REPORTS: '/admin/analytics/reports',
  },
  SETTINGS: {
    LIST: '/admin/settings',
    UPDATE: '/admin/settings',
  },
  ADMINS: {
    LIST: '/admin/admins',
    DETAILS: (id: string) => `/admin/admins/${id}`,
    CREATE: '/admin/admins',
    UPDATE: (id: string) => `/admin/admins/${id}`,
    UPDATE_STATUS: (id: string) => `/admin/admins/${id}/status`,
    DELETE: (id: string) => `/admin/admins/${id}`,
  },
  AUDIT_LOGS: {
    LIST: '/admin/audit-logs',
    DETAILS: (id: string) => `/admin/audit-logs/${id}`,
    EXPORT: '/admin/audit-logs/export',
  },
} as const

export type ApiEndpoint =
  (typeof API_ENDPOINTS)[keyof typeof API_ENDPOINTS][keyof (typeof API_ENDPOINTS)[keyof typeof API_ENDPOINTS]]
