export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/admin/auth/login',
    REFRESH_TOKEN: '/admin/auth/refresh-token',
    LOGOUT: '/admin/auth/logout',
    FORGOT_PASSWORD: '/admin/auth/forgot-password',
    RESET_PASSWORD: '/admin/auth/reset-password',
    ME: '/admin/auth/me',
  },
  PROFILE: {
    GET: '/admin/profile',
    UPDATE: '/admin/profile',
    CHANGE_PASSWORD: '/admin/profile/password',
    UPLOAD_AVATAR: '/admin/profile/avatar',
  },
  DASHBOARD: {
    STATS: '/admin/dashboard',
    OVERVIEW: '/admin/dashboard/overview',
    STATISTICS: '/admin/dashboard/statistics',
    RECENT_ACTIVITIES: '/admin/dashboard/recent-activities',
    RECENT_BOOKINGS: '/admin/dashboard/recent-bookings',
    RECENT_REVIEWS: '/admin/dashboard/recent-reviews',
    RECENT_REPORTS: '/admin/dashboard/recent-reports',
  },
  STUDENTS: {
    LIST: '/admin/students',
    STATISTICS: '/admin/students/statistics',
    EXPORT: '/admin/students/export',
    DETAILS: (id: string) => `/admin/students/${id}`,
    UPDATE: (id: string) => `/admin/students/${id}`,
    UPDATE_STATUS: (id: string) => `/admin/students/${id}/status`,
    SUSPEND: (id: string) => `/admin/students/${id}/suspend`,
    UNSUSPEND: (id: string) => `/admin/students/${id}/unsuspend`,
    DELETE: (id: string) => `/admin/students/${id}`,
    BOOKINGS: (id: string) => `/admin/students/${id}/bookings`,
  },
  ARTISANS: {
    LIST: '/admin/artisans',
    STATISTICS: '/admin/artisans/statistics',
    EXPORT: '/admin/artisans/export',
    DETAILS: (id: string) => `/admin/artisans/${id}`,
    SERVICES: (id: string) => `/admin/artisans/${id}/services`,
    PORTFOLIO: (id: string) => `/admin/artisans/${id}/portfolio`,
    AVAILABILITY: (id: string) => `/admin/artisans/${id}/availability`,
    UPDATE: (id: string) => `/admin/artisans/${id}`,
    UPDATE_STATUS: (id: string) => `/admin/artisans/${id}/status`,
    SUSPEND: (id: string) => `/admin/artisans/${id}/suspend`,
    UNSUSPEND: (id: string) => `/admin/artisans/${id}/unsuspend`,
    DELETE: (id: string) => `/admin/artisans/${id}`,
  },
  VERIFICATIONS: {
    LIST: '/v1/admin/verification',
    STATISTICS: '/v1/admin/verification/statistics',
    DETAILS: (id: string) => `/v1/admin/verification/${id}`,
    DOCUMENTS: (id: string) => `/v1/admin/verification/${id}/documents`,
    APPROVE: (id: string) => `/v1/admin/verification/${id}/approve`,
    REJECT: (id: string) => `/v1/admin/verification/${id}/reject`,
    REQUEST_CHANGES: (id: string) => `/v1/admin/verification/${id}/request-changes`,
    ADD_NOTE: (id: string) => `/v1/admin/verification/${id}/note`,
    UPDATE_STATUS: (id: string) => `/v1/admin/verification/${id}/status`,
  },
  CATEGORIES: {
    LIST: '/admin/categories',
    STATISTICS: '/admin/categories/statistics',
    DETAILS: (id: string) => `/admin/categories/${id}`,
    CREATE: '/admin/categories',
    UPDATE: (id: string) => `/admin/categories/${id}`,
    DELETE: (id: string) => `/admin/categories/${id}`,
  },
  BOOKINGS: {
    LIST: '/admin/bookings',
    STATISTICS: '/admin/bookings/statistics',
    DETAILS: (id: string) => `/admin/bookings/${id}`,
    UPDATE_STATUS: (id: string) => `/admin/bookings/${id}/status`,
    CANCEL: (id: string) => `/admin/bookings/${id}/cancel`,
    COMPLETE: (id: string) => `/admin/bookings/${id}/complete`,
  },
  REVIEWS: {
    LIST: '/admin/reviews',
    STATISTICS: '/admin/reviews/statistics',
    DETAILS: (id: string) => `/admin/reviews/${id}`,
  },
  REPORTS: {
    LIST: '/v1/admin/reports',
    STATISTICS: '/v1/admin/reports/statistics',
    EXPORT: '/v1/admin/reports/export',
    DETAILS: (id: string) => `/v1/admin/reports/${id}`,
    UPDATE_STATUS: (id: string) => `/v1/admin/reports/${id}/status`,
    ASSIGN: (id: string) => `/v1/admin/reports/${id}/assign`,
    RESOLVE: (id: string) => `/v1/admin/reports/${id}/resolve`,
    DISMISS: (id: string) => `/v1/admin/reports/${id}/dismiss`,
    ADD_NOTE: (id: string) => `/v1/admin/reports/${id}/note`,
  },
  NOTIFICATIONS: {
    LIST: '/admin/notifications',
    STATISTICS: '/admin/notifications/statistics',
    CREATE: '/admin/notifications',
    BROADCAST: '/admin/notifications/broadcast',
    UPDATE: (id: string) => `/admin/notifications/${id}`,
    DELETE: (id: string) => `/admin/notifications/${id}`,
  },
  ANALYTICS: {
    BASE: '/admin/analytics',
    OVERVIEW: '/admin/analytics/overview',
    USERS: '/admin/analytics/users',
    BOOKINGS: '/admin/analytics/bookings',
    REVIEWS: '/admin/analytics/reviews',
    REPORTS: '/admin/analytics/reports',
    CATEGORIES: '/admin/analytics/categories',
    REVENUE: '/admin/analytics/revenue',
    TOP_CATEGORIES: '/analytics/top-categories',
  },
  SETTINGS: {
    GET: '/admin/settings',
    UPDATE: '/admin/settings',
  },
  USERS: {
    LIST: '/admin/users',
    STUDENTS: '/admin/users/students',
    ARTISANS: '/admin/users/artisans',
    ADMINS: '/admin/users/admins',
    DETAILS: (id: string) => `/admin/users/${id}`,
    CREATE: '/admin/users',
    UPDATE: (id: string) => `/admin/users/${id}`,
    UPDATE_STATUS: (id: string) => `/admin/users/${id}/status`,
    DELETE: (id: string) => `/admin/users/${id}`,
  },
  AUDIT_LOGS: {
    LIST: '/admin/audit-logs',
    EXPORT: '/admin/audit-logs/export',
    DETAILS: (id: string) => `/admin/audit-logs/${id}`,
  },
  PORTFOLIO: {
    LIST: '/admin/portfolio',
    DELETE: (id: string) => `/admin/portfolio/${id}`,
  },
  CMS: {
    LIST: '/admin/cms',
    CREATE: '/admin/cms',
    UPDATE: (id: string) => `/admin/cms/${id}`,
    DELETE: (id: string) => `/admin/cms/${id}`,
  },
  UPLOADS: {
    GET: '/admin/uploads',
  },
  PAYMENTS: {
    LIST: '/admin/payments',
    DETAILS: (id: string) => `/admin/payments/${id}`,
  },
  ARTISAN_APPLICATIONS: {
    LIST: '/admin/applications',
    DETAILS: (id: string) => `/admin/applications/${id}`,
    STATISTICS: '/admin/applications/statistics',
    APPROVE: (id: string) => `/admin/applications/${id}/approve`,
    REJECT: (id: string) => `/admin/applications/${id}/reject`,
    REQUEST_CHANGES: (id: string) => `/admin/applications/${id}/request-changes`,
    UPDATE_STATUS: (id: string) => `/admin/applications/${id}/status`,
  },
  SKILLS: {
    LIST: '/admin/skills',
    DETAILS: (id: string) => `/admin/skills/${id}`,
    CREATE: '/admin/skills',
    UPDATE: (id: string) => `/admin/skills/${id}`,
    DELETE: (id: string) => `/admin/skills/${id}`,
  },
} as const

export type ApiEndpoint =
  (typeof API_ENDPOINTS)[keyof typeof API_ENDPOINTS][keyof (typeof API_ENDPOINTS)[keyof typeof API_ENDPOINTS]]
